import streamlit as st
import requests
import pandas as pd
import joblib
import numpy as np
from datetime import datetime, timedelta
import os
from dotenv import load_dotenv

load_dotenv()

API_URL = os.getenv("API_URL", "http://127.0.0.1:8000")

st.set_page_config(page_title="Solar Forecast", page_icon="☀️")
st.title("☀️ Solar Power Generation Forecast")
st.caption("📍 Location: Bengaluru, India — Plant 1, Inverter 1BY6WEcLGh8j5v7")

# ── Date picker (restricted to next 7 days) ───────────────
today = datetime.now().date()
max_date = today + timedelta(days=7)

selected_date = st.date_input(
    "Select a date to forecast",
    value=today,
    min_value=today,
    max_value=max_date
)

st.caption("⚠️ Predictions are based on historical time patterns only and do not account for real weather conditions.")

# ── Generate 24 hours for selected date ───────────────────
hours = [
    datetime(selected_date.year, selected_date.month, selected_date.day, h)
    for h in range(24)
]

# ── Load scaler for lag normalization ─────────────────────
scaler = joblib.load('models/scaler.pkl')

# ── Call API for each hour ─────────────────────────────────
predictions_real = []
predictions_scaled = []

for i, hour in enumerate(hours):
    lag_1 = predictions_scaled[i-1] if i > 0 else 0.0
    rolling_mean_3 = float(np.mean(predictions_scaled[max(0, i-3):i])) if i > 0 else 0.0

    payload = {
        "hour": hour.hour,
        "day_of_week": hour.weekday(),
        "month": hour.month,
        "lag_1": lag_1,
        "rolling_mean_3": rolling_mean_3
    }

    try:
        response = requests.post(f"{API_URL}/predict", json=payload)
        result = response.json()
        real_val = result["predicted_ac_power"]
        scaled_val = float(scaler.transform([[real_val]])[0][0])
        predictions_real.append(round(max(0.0, real_val), 2))
        predictions_scaled.append(max(0.0, scaled_val))
    except:
        predictions_real.append(0.0)
        predictions_scaled.append(0.0)

# ── Build dataframe ────────────────────────────────────────
df = pd.DataFrame({
    "Time": [h.strftime("%H:%M") for h in hours],
    "Predicted AC Power (W)": predictions_real
})

# ── Total energy metric ────────────────────────────────────
total_energy = sum(predictions_real)

st.metric(
    label="Total Predicted Energy for the Day",
    value=f"{total_energy:,.0f} W"
)

# ── Chart ──────────────────────────────────────────────────
st.subheader(f"24-Hour Forecast — {selected_date.strftime('%d %b %Y')}")
st.line_chart(df.set_index("Time"))

# ── Table ──────────────────────────────────────────────────
st.subheader("Hourly Breakdown")
st.dataframe(df, use_container_width=True)

# ── About the Model ────────────────────────────────────────
st.divider()
st.subheader("📖 About the Model")

st.markdown("""
**What is this model?**  
This forecast is generated by a Long Short-Term Memory (LSTM) neural network — a type of deep learning 
model specifically designed to learn patterns in sequential and time-series data. It was built using 
TensorFlow and Keras in Python.

**What data was it trained on?**  
The model was trained on 34 days of historical inverter-level solar generation data recorded between 
May and June 2020 from a single solar plant in Bengaluru, India. The dataset was sourced from Kaggle 
and contains AC power readings at 15-minute intervals, which were resampled to hourly intervals during 
preprocessing. One inverter (ID: 1BY6WEcLGh8j5v7) was selected out of 22 available inverters to keep 
the model focused and the pipeline straightforward.

**How does it make predictions?**  
The model uses five input features to estimate AC power output for each hour:
- Hour of the day
- Day of the week
- Month of the year
- Previous hour's generation (lag feature)
- Average generation over the last 3 hours (rolling mean)

**Model Performance**  
The model achieved a Test MSE (Mean Squared Error) of **0.0105** on normalized data (scale of 0 to 1).  
In plain terms, this means the model's predictions deviate by approximately 1% from actual normalized 
generation values on average, indicating a reasonable fit for the time patterns present in the 
training data.

**Important: Understanding What This Forecast Actually Represents**  
This dashboard does not produce a true real-time forecast. Since the model was trained on historical 
data from May–June 2020, its predictions represent estimated generation based on the time patterns 
learned from that period. The model has no knowledge of current weather conditions, cloud cover, 
temperature, or any real-world factors affecting generation today. Forecasts should be interpreted 
as "what a typical hour in this month historically looked like" rather than an actual prediction 
of today's or tomorrow's generation.

**Limitations**  
- Trained on only 34 days of data from a single season, limiting accuracy across other months and years  
- Does not incorporate real-time or forecast weather data such as irradiance, cloud cover, or temperature  
- Predictions for future dates are pattern-based estimates, not true forecasts  
- Does not account for solar panel degradation, dust accumulation, or equipment faults over time  
- A production-grade system would require continuous retraining on recent data and integration 
with a live weather API such as Open-Meteo or NASA POWER  
""")